import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    padding: 20,
  },
  top: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0F172A",
  },
  sub: {
    fontSize: 14,
    color: "#64748B",
    marginTop: 2,
  },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2563EB",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 6,
  },
  addTxt: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 14,
  },
  search: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    fontSize: 14,
    marginBottom: 16,
  },
  tableContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    flex: 1,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#F1F5F9",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  headerCell: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
    textTransform: "uppercase",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    alignItems: "center",
  },
  cell: {
    fontSize: 14,
    color: "#1E293B",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modal: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    marginVertical: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    marginBottom: 14,
    backgroundColor: "#F8FAFC",
  },
  ageGroupContainer: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 10,
    marginBottom: 14,
    backgroundColor: "#F8FAFC",
  },
  picker: {
    height: 50,
    color: "#1E293B",
  },
  save: {
    backgroundColor: "#2563EB",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  saveText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
  },
  cancelBtn: {
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  cancelText: {
    color: "#64748B",
    fontSize: 16,
  },
  viewModal: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginVertical: 20,
  },
  viewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  viewName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0F172A",
  },
  viewReg: {
    fontSize: 14,
    color: "#64748B",
    marginTop: 4,
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    padding: 4,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 8,
  },
  activeTab: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#94A3B8",
  },
  activeTabText: {
    color: "#2563EB",
    fontWeight: "600",
  },
  viewContent: {
    paddingTop: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0F172A",
    marginBottom: 16,
  },
  infoSection: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
  },
  infoGrid: {
    gap: 16,
  },
  infoItem: {
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingBottom: 12,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 14,
    color: "#1E293B",
  },
  attendanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  navigationButtons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  navButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F0F7FF",
  },
  yearText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
    minWidth: 60,
    textAlign: "center",
  },
  attendanceSummary: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  summaryItem: {
    alignItems: "center",
  },
  summaryNumber: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0F172A",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 4,
  },
  summaryDivider: {
    width: 1,
    height: 40,
    backgroundColor: "#E2E8F0",
  },
  horizontalScrollView: {
    flexGrow: 0,
    marginBottom: 8,
  },
  horizontalMonthContainer: {
    flexDirection: "row",
    gap: 16,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  monthColumn: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    minWidth: 80,
  },
  monthColumnHeader: {
    alignItems: "center",
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  monthColumnTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 4,
  },
  monthColumnStats: {
    flexDirection: "row",
    gap: 8,
  },
  monthColumnStatText: {
    fontSize: 10,
    fontWeight: "500",
    color: "#64748B",
  },
  dayOfWeekHeaders: {
    flexDirection: "row",
    marginBottom: 4,
    justifyContent: "flex-start",
  },
  dayOfWeekHeaderCell: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 4,
    minWidth: 28,
  },
  dayOfWeekHeaderText: {
    fontSize: 9,
    fontWeight: "600",
    color: "#94A3B8",
    textAlign: "center",
  },
  sessionDaysColumn: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  sessionDayCell: {
    flex: 1,
    alignItems: "center",
    gap: 3,
    paddingVertical: 2,
    minWidth: 28,
  },
  sessionDayNumber: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginVertical: 1,
  },
  sessionDayNumberPresent: {
    backgroundColor: "#DCFCE7",
    borderColor: "#86EFAC",
  },
  sessionDayNumberAbsent: {
    backgroundColor: "#FEE2E2",
    borderColor: "#FCA5A5",
  },
  sessionDayNumberToday: {
    backgroundColor: "#DBEAFE",
    borderWidth: 2,
    borderColor: "#3B82F6",
  },
  sessionDayNumberText: {
    fontSize: 10,
    fontWeight: "500",
    color: "#1E293B",
  },
  sessionDayNumberTextPresent: {
    color: "#166534",
  },
  sessionDayNumberTextAbsent: {
    color: "#991B1B",
  },
  sessionDayNumberTextToday: {
    color: "#1D4ED8",
    fontWeight: "500",
  },
  legendContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    marginTop: 8,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  legendDotPresent: {
    backgroundColor: "#86EFAC",
  },
  legendDotAbsent: {
    backgroundColor: "#FCA5A5",
  },
  legendDotSession: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  legendDotToday: {
    backgroundColor: "#DBEAFE",
    borderWidth: 2,
    borderColor: "#3B82F6",
  },
  legendText: {
    fontSize: 12,
    color: "#64748B",
  },
  overallAttendance: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  attendanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  attendanceLabel: {
    fontSize: 14,
    color: "#1E293B",
    fontWeight: "500",
  },
  attendanceBarContainer: {
    marginTop: 4,
  },
  attendancePercentage: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0F172A",
    marginBottom: 8,
  },
  progressBar: {
    height: 8,
    backgroundColor: "#E2E8F0",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#2563EB",
    borderRadius: 4,
  },
  // Payment Styles
  paymentStudentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  paymentStudentName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0F172A",
  },
  paymentStudentMeta: {
    fontSize: 14,
    color: "#64748B",
    marginTop: 2,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  backButtonText: {
    fontSize: 14,
    color: "#2563EB",
    fontWeight: "500",
  },
  paymentSummaryCards: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  paymentCard: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  paymentCardLabel: {
    fontSize: 12,
    color: "#94A3B8",
    fontWeight: "500",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  paymentCardValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0F172A",
  },
  outstandingValue: {
    color: "#EF4444",
  },
  paymentSummary: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  paymentStatCard: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  paymentStatLabel: {
    fontSize: 12,
    color: "#94A3B8",
    fontWeight: "500",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  paymentStatValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
  },
  transactionList: {
    gap: 8,
  },
  transactionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  transactionInfo: {
    flex: 1,
  },
  transactionMonth: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0F172A",
  },
  transactionDate: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 2,
  },
  transactionDetails: {
    alignItems: "flex-end",
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0F172A",
  },
  transactionStatus: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 4,
  },
  statusPaid: {
    backgroundColor: "#00f957",
  },
  statusPending: {
    backgroundColor: "#22C55E",
  },
  transactionStatusText: {
    fontSize: 11,
    fontWeight: "600",
  },
  statusPaidText: {
    color: "#166534",
  },
  statusPendingText: {
    color: "#ffffff",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 14,
    color: "#94A3B8",
    marginTop: 12,
  },


inputContainer: {
  marginBottom: 12,
  width: '100%',
},

inputError: {
  borderColor: '#EF4444',
  borderWidth: 1,
},

errorText: {
  color: '#EF4444',
  fontSize: 12,
  marginTop: 4,
  marginLeft: 4,
},
});